export const KrInitialState = {
  isTotal: false,
  isSeoul: false,
  isGyeonggi: false,
  isIncheon: false,
  isGangwon: false,
  isSejong: false,
  isChungbuk: false,
  isChungnam: false,
  isDaejeon: false,
  isGyeongbuk: false,
  isJeonbuk: false,
  isDaegu: false,
  isJeonnam: false,
  isGwangju: false,
  isGyeongnam: false,
  isUlsan: false,
  isBusan: false,
  isJeju: false,
  isLazaretto: false,
};
